(define (fsave txt fln)	
	(set! utt1 (utt.synth (eval (list 'Utterance 'Text txt))))
	(utt.save.wave utt1 fln 'riff)
)

(define (wsave txt fln)	
	(set! utt1 (utt.synth (eval (list 'Utterance 'Words txt))))
	(utt.save.wave utt1 fln 'riff)
)

(language_russian)
(fsave "приготовьтесь" "prepare.wav")
(fsave "выполните разворот" "make_uturn.wav")
(fsave "поверните налево " "left.wav")
(fsave "резко поверните налево " "left_sh.wav")
(fsave "плавно поверните налево" "left_sl.wav")
(fsave "поверните направо " "right.wav")
(fsave "резко поверните направо " "right_sh.wav")
(fsave "плавно поверните направо" "right_sl.wav")
(fsave "резко поверните направо " "right_sh.wav")
(fsave "держитесь правее" "right_keep.wav")
(fsave "держитесь левее" "left_keep.wav")
(fsave "продолжайте движение" "go_ahead.wav")
(fsave "прямо" "straight.wav")
(fsave "круг" "roundabout.wav")
(fsave "съезд" "exit.wav")

(fsave "через" "in.wav")
(fsave "более чем" "more_than.wav")


(fsave "метр" "metr.wav")
(fsave "метров" "metrov.wav")
(fsave "метра" "metra.wav")
(fsave "километр" "kilometr.wav")
(fsave "километров" "kilometrov.wav")
(fsave "километра" "kilometra.wav")


(fsave "и вы прибудете в пункт назначения" "and_arrive_destination.wav")
(fsave "и вы прибудете в промежуточный пункт " "and_arrive_intermediate.wav")
(fsave "вы прибыли в пункт назначения" "reached_destination.wav")
(fsave "вы прибыли в промежуточный пункт " "reached_intermediate.wav")
(fsave "маршрут составляет " "route_new_calc.wav")
(fsave "маршрут пересчитывается, расстояние " "route_recalc.wav")
;;(wsave (list "Потерян" "сигнал" "ДЖИ," "ПИИ," "ЭЭС" ) "location_lost.wav")

(fsave "ДЖИПИИЭС потерян сигнал" "location_lost.wav")

(fsave "вы отклонились от маршрута" "off_route.wav")
(fsave "внимание" "attention.wav")
(fsave "вы превысили разрешённую скорость" "speed_alarm.wav")

(fsave "первый" "1th.wav")
(fsave "второй" "2th.wav")
(fsave "третий" "3th.wav")
(fsave "четвертый" "4th.wav")
(fsave "пятый" "5th.wav")
(fsave "шестой" "6th.wav")
(fsave "седьмой" "7th.wav")
(fsave "восьмой" "8th.wav")
(fsave "девятый" "9th.wav")
(fsave "десятый" "10th.wav")
(fsave "одиннадцатый" "11th.wav")
(fsave "двенадцатый" "12th.wav")
(fsave "тринадцатый" "13th.wav")
(fsave "четырнадцатый" "14th.wav")

(fsave "10" "10.wav")
(fsave "20" "20.wav")
(fsave "30" "30.wav")
(fsave "40" "40.wav")
(fsave "50" "50.wav")
(fsave "60" "60.wav")
(fsave "70" "70.wav")
(fsave "80" "80.wav")
(fsave "90" "90.wav")

(fsave "100" "100.wav")
(fsave "200" "200.wav")
(fsave "300" "300.wav")
(fsave "400" "400.wav")
(fsave "500" "500.wav")
(fsave "600" "600.wav")
(fsave "700" "700.wav")
(fsave "800" "800.wav")
(fsave "900" "900.wav")
(fsave "1000" "1000.wav")
