cp -f ../../android/OsmAnd/res/values/phrases.xml phrases/en/
cp -f ../../android/OsmAnd/res/values-be/phrases.xml phrases/be/
cp -f ../../android/OsmAnd/res/values-ca/phrases.xml phrases/ca/
cp -f ../../android/OsmAnd/res/values-da/phrases.xml phrases/da/
cp -f ../../android/OsmAnd/res/values-de/phrases.xml phrases/de/
cp -f ../../android/OsmAnd/res/values-es/phrases.xml phrases/es/
cp -f ../../android/OsmAnd/res/values-fr/phrases.xml phrases/fr/
cp -f ../../android/OsmAnd/res/values-hu/phrases.xml phrases/hu/
cp -f ../../android/OsmAnd/res/values-is/phrases.xml phrases/is/
cp -f ../../android/OsmAnd/res/values-it/phrases.xml phrases/it/
cp -f ../../android/OsmAnd/res/values-pl/phrases.xml phrases/pl/
cp -f ../../android/OsmAnd/res/values-pt/phrases.xml phrases/pt/
cp -f ../../android/OsmAnd/res/values-ru/phrases.xml phrases/ru/
cp -f ../../android/OsmAnd/res/values-sk/phrases.xml phrases/sk/
cp -f ../../android/OsmAnd/res/values-sl/phrases.xml phrases/sl/
cp -f ../../android/OsmAnd/res/values-fa/phrases.xml phrases/fa/
cp -f ../../android/OsmAnd/res/values-my/phrases.xml phrases/my/
cp -f ../../android/OsmAnd/res/values-ar/phrases.xml phrases/ar/
cp -f ../../android/OsmAnd/res/values-nl/phrases.xml phrases/nl/
cp -f ../../android/OsmAnd/res/values-cs/phrases.xml phrases/cs/
cp -f ../../android/OsmAnd/res/values-gl/phrases.xml phrases/gl/
cp -f ../../android/OsmAnd/res/values-tr/phrases.xml phrases/tr/
cp -f ../../android/OsmAnd/res/values-uk/phrases.xml phrases/uk/

cp -f ../../android/OsmAnd/res/values-b+hsb/phrases.xml phrases/hsb/
#cp -f ../../android/OsmAnd/res/values-ku/phrases.xml phrases/ku/
cp -f ../../android/OsmAnd/res/values-nb/phrases.xml phrases/nb/
cp -f ../../android/OsmAnd/res/values-oc/phrases.xml phrases/oc/
#cp -f ../../android/OsmAnd/res/values-ro/phrases.xml phrases/ro/
cp -f ../../android/OsmAnd/res/values-sc/phrases.xml phrases/sc/
cp -f ../../android/OsmAnd/res/values-sq/phrases.xml phrases/sq/

#cp -f ../../android/OsmAnd/res/values-zh-rCN/phrases.xml phrases/zh/
#cp -f ../../android/OsmAnd/res/values-zh-rHK/phrases.xml phrases/zh/
#cp -f ../../android/OsmAnd/res/values-zh-rTW/phrases.xml phrases/zh/
