# This adds a comment to a PR with a link to any build artifacts. This is done in a separate workflow so it can also run with write permissions on a PR from
# a third-party repository. The PR-triggered workflow itself is limited in permissions, e.g.
# https://docs.github.com/en/actions/how-tos/security-for-github-actions/security-guides/use-github_token-in-workflows#modifying-the-permissions-for-the-github_token
# says:
#
# > You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access. The exception to
# > this behavior is where an admin user has selected the Send write tokens to workflows from pull requests option in the GitHub Actions settings.
#
# However, *this* followup workflow runs from the default branch (so any changes to this workflow in the PR are not reflected, the definintion from the main
# default is always used), so it can run with full permissions (without having to grant full write permissions to all PR submitters).
#
# Note that originally, this was also a separate workflow because the URL for uploaded artifacts was only available after a workflow completed, but with
# actions/upload-artifact@v4 the url is available right away, so this is no longer a reason for using a separate workflow.
name: Linking to artifacts in PR
on:
  workflow_run:
    workflows: ["Build OSF file"]
    types: [completed]

jobs:
  artifacts-url-comments:
    name: Add artifact links to PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # This uses a third-party action that handles figuring out the
      # pull request to comment on (which is no longer easily available
      # in a followup workflow) and formatting the comment.
      - name: Add artifact links to PR and issues
        uses: tonyhallett/artifacts-url-comments@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prefix: "Automatically generated build artifacts for commit ${{ github.event.workflow_run.head_sha }} (note: these links will expire after some time):\n"
          format: " - {name}: [:arrow_double_down: Download]({url})"
          # This adds a hline to terminate the artifact list, just
          # newlines should work, but it seems they are eaten
          # somewhere...
          suffix: "---\n\nTo test this PR, download the OSF file and open it with Osmand\n"
